# Generated by Django 5.2.7 on 2025-10-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='NAGAAD HALLS', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('price_per_guest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('income_account', models.CharField(max_length=100)),
                ('extra_income_account', models.CharField(max_length=100)),
                ('receivable_account', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
